name: tryapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # speech_to_text: ^3.1.0
  firebase_auth: ^3.0.2
  camera: ^0.8.1+7
  image_picker: ^0.8.3+3
  cloud_firestore: ^2.5.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  flutter_spinkit: ^5.0.0
  number_inc_dec: ^0.7.0
  html: ^0.15.0
  avatar_glow: ^2.0.1
  speech_to_text: ^5.0.0
  async_button_builder: ^2.0.7
  # icon_picker: ^1.0.0
  deep_collection: ^1.0.1
  intl: ^0.17.0
  pdf: ^3.4.2
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  ext_storage: ^1.0.0
  photo_view: ^0.12.0
  dio:
  ndialog:
  firebase_storage:
  video_player:
  chewie:
  cached_network_image:
  animations:
  flutter_staggered_animations:
  flutter_local_notifications:
  firebase_messaging: ^10.0.6
  stacked_cli: ^1.0.16

  # speech_recognition: ^0.3.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  injectable: ^1.5.0
  stacked_services: ^0.8.13
  # camera:
  # image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
  #   sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/piclog.png
    - assets/gifmessage.gif
    - assets/download.png
    - assets/errorp.png
    - assets/patientavatar.png
    - assets/nurseavatar.png
    - assets/therapistavatar.png
    - assets/nodata.png
    # - assets/doc(1).png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
